### ISSUE TITLE
Android build fails due incorrect assembly versions

### ISSUE THREAD

**Issue by stefanfisk** [anaisbetts/starter-mobile#9]
When trying to build on Xamarin Studio alpha (4.3.0, build 52), I get the following errors for the Android project:

```
Error CS1705: Assembly `Akavache, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null' references `System.Reactive.Core, Version=2.1.30214.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version number than imported assembly `System.Reactive.Core, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' (CS1705) (Tunaspot-Android)
Error CS1705: Assembly `Akavache, Version=3.1.2.0, Culture=neutral, PublicKeyToken=null' references `System.Reactive.Interfaces, Version=2.1.30214.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' which has a higher version number than imported assembly `System.Reactive.Interfaces, Version=0.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' (CS1705) (Tunaspot-Android)
```

**Comment by anaisbetts** [comment]
I'll have a look, thanks for the report

**Comment by stefanfisk** [comment]
8befc7d9a00c069db08947918a384c5b9332cc85 seems to be working fine. Same for #7.

**Comment by anaisbetts** [comment]
This should be fixed now
